In [1]:
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import NearestNeighbors

In [3]:
articles = pd.read_parquet("../../../data/gold/articles.parquet")

articles.shape

(105542, 14)

In [4]:
categorical_cols = [
    "product_type_name",
    "product_group_name",
    "graphical_appearance_name",
    "colour_group_name",
    "perceived_colour_value_name",
    "perceived_colour_master_name",
    "department_name",
    "index_name",
    "index_group_name",
    "section_name",
    "garment_group_name"
]

In [5]:
encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=True
)

categorical_matrix = encoder.fit_transform(articles[categorical_cols])

categorical_matrix.shape

(105542, 600)

In [6]:
nn_model = NearestNeighbors(
    metric="cosine",
    algorithm="brute"
)

nn_model.fit(categorical_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [7]:
query_idx = 0

distances, indices = nn_model.kneighbors(
    categorical_matrix[query_idx],
    n_neighbors=11
)

distances, indices

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[     0, 102303,  76305, 101064, 102963,   5317, 101344,  77177,
          77092,  35623,  72486]]))

In [8]:
query_idx = 0

neighbor_indices = indices[0][1:]
neighbor_distances = distances[0][1:]

display_cols = [
    "article_id",
    "prod_name",
    "product_type_name",
    "colour_group_name",
    "section_name",
    "garment_group_name"
]

query_product = articles.iloc[[query_idx]][display_cols]

recommendations = articles.iloc[neighbor_indices][display_cols].copy()
recommendations["cosine_similarity"] = 1 - neighbor_distances

query_product, recommendations

(   article_id  prod_name product_type_name colour_group_name  \
 0   108775015  Strap top          Vest top             Black

              section_name garment_group_name
 0  Womens Everyday Basics       Jersey Basic  ,
         article_id                   prod_name product_type_name  \
 102303   903309001         V-neck straptop 3-p          Vest top
 76305    784338001              Petra seamless          Vest top
 101064   893994001  V-Neck Strap Top Long 2-pk          Vest top
 102963   908230001         Moa rib 2-pack tank          Vest top
 5317     494030013                    Tika (1)          Vest top
 101344   895993001                    Dag Tank          Vest top
 77177    788261001                 Amanda Tank          Vest top
 77092    787946002             Moa 2 pack tank          Vest top
 35623    647505001                  Perth tank          Vest top
 72486    767834001                  Strap Top.          Vest top

        colour_group_name            section_name garment_group_name  \
 102303             Black  Womens Everyday Basics       Jersey Basic
 76305              Black  Womens Everyday Basics       Jersey Basic
 101064             Black  Womens Everyday Basics       Jersey Basic
 102963             Black  Womens Everyday Basics       Jersey Basic
 5317               Black  Womens Everyday Basics       Jersey Basic
 101344             Black  Womens Everyday Basics       Jersey Basic
 77177              Black  Womens Everyday Basics       Jersey Basic
 77092              Black  Womens Everyday Basics       Jersey Basic
 35623              Black  Womens Everyday Basics       Jersey Basic
 72486              Black  Womens Everyday Basics       Jersey Basic

         cosine_similarity
 102303                1.0
 76305                 1.0
 101064                1.0
 102963                1.0
 5317                  1.0
 101344                1.0
 77177                 1.0
 77092                 1.0
 35623                 1.0
 72486                 1.0  )

In [12]:
def get_similar_products(article_id, top_k=10):
    matching_indices = articles.index[
        articles["article_id"] == article_id
    ].tolist()

    if not matching_indices:
        raise ValueError(f"article_id bulunamadı: {article_id}")

    query_idx = matching_indices[0]

    # Biraz fazla komşu isteyelim ki kendisini çıkardıktan sonra top_k ürün kalsın
    distances, indices = nn_model.kneighbors(
        categorical_matrix[query_idx],
        n_neighbors=top_k + 5
    )

    neighbor_indices = indices[0]
    neighbor_distances = distances[0]

    # Sorgu ürününün kendisini açıkça çıkar
    filtered_neighbors = [
        (idx, dist)
        for idx, dist in zip(neighbor_indices, neighbor_distances)
        if idx != query_idx
    ]

    # İlk top_k sonucu al
    filtered_neighbors = filtered_neighbors[:top_k]

    neighbor_indices = [idx for idx, _ in filtered_neighbors]
    neighbor_distances = [dist for _, dist in filtered_neighbors]

    display_cols = [
        "article_id",
        "prod_name",
        "product_type_name",
        "colour_group_name",
        "section_name",
        "garment_group_name"
    ]

    query_product = articles.iloc[[query_idx]][display_cols]

    recommendations = articles.iloc[neighbor_indices][display_cols].copy()
    recommendations["cosine_similarity"] = 1 - pd.Series(
        neighbor_distances,
        index=recommendations.index
    )

    return query_product, recommendations

In [10]:
query_product, recommendations = get_similar_products(
    article_id=108775015,
    top_k=10
)

query_product, recommendations

(   article_id  prod_name product_type_name colour_group_name  \
 0   108775015  Strap top          Vest top             Black

              section_name garment_group_name
 0  Womens Everyday Basics       Jersey Basic  ,
         article_id                   prod_name product_type_name  \
 102303   903309001         V-neck straptop 3-p          Vest top
 76305    784338001              Petra seamless          Vest top
 101064   893994001  V-Neck Strap Top Long 2-pk          Vest top
 102963   908230001         Moa rib 2-pack tank          Vest top
 5317     494030013                    Tika (1)          Vest top
 101344   895993001                    Dag Tank          Vest top
 77177    788261001                 Amanda Tank          Vest top
 77092    787946002             Moa 2 pack tank          Vest top
 35623    647505001                  Perth tank          Vest top
 72486    767834001                  Strap Top.          Vest top

        colour_group_name            section_name garment_group_name  \
 102303             Black  Womens Everyday Basics       Jersey Basic
 76305              Black  Womens Everyday Basics       Jersey Basic
 101064             Black  Womens Everyday Basics       Jersey Basic
 102963             Black  Womens Everyday Basics       Jersey Basic
 5317               Black  Womens Everyday Basics       Jersey Basic
 101344             Black  Womens Everyday Basics       Jersey Basic
 77177              Black  Womens Everyday Basics       Jersey Basic
 77092              Black  Womens Everyday Basics       Jersey Basic
 35623              Black  Womens Everyday Basics       Jersey Basic
 72486              Black  Womens Everyday Basics       Jersey Basic

         cosine_similarity
 102303                1.0
 76305                 1.0
 101064                1.0
 102963                1.0
 5317                  1.0
 101344                1.0
 77177                 1.0
 77092                 1.0
 35623                 1.0
 72486                 1.0  )

In [13]:
test_article_ids = [
    108775015,  # Strap top
    681107007,  # Dress
    686284001,  # Sweater
    754256001,  # Bra
    755712001   # Shirt
]

for article_id in test_article_ids:
    query_product, recommendations = get_similar_products(
        article_id=article_id,
        top_k=5
    )

    print("\nQUERY PRODUCT")
    display(query_product)

    print("RECOMMENDATIONS")
    display(recommendations)

QUERY PRODUCT

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name
0,108775015,Strap top,Vest top,Black,Womens Everyday Basics,Jersey Basic

RECOMMENDATIONS

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name,cosine_similarity
102303,903309001,V-neck straptop 3-p,Vest top,Black,Womens Everyday Basics,Jersey Basic,1.0
76305,784338001,Petra seamless,Vest top,Black,Womens Everyday Basics,Jersey Basic,1.0
101064,893994001,V-Neck Strap Top Long 2-pk,Vest top,Black,Womens Everyday Basics,Jersey Basic,1.0
102963,908230001,Moa rib 2-pack tank,Vest top,Black,Womens Everyday Basics,Jersey Basic,1.0
5317,494030013,Tika (1),Vest top,Black,Womens Everyday Basics,Jersey Basic,1.0

QUERY PRODUCT

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name
44708,681107007,Dahlia,Dress,Blue,Kids Girl,Dresses/Skirts girls

RECOMMENDATIONS

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name,cosine_similarity
64805,742918001,Baton Rouge Dress,Dress,Blue,Kids Girl,Dresses/Skirts girls,1.000000
83213,811530001,Hampus Dress,Dress,Blue,Kids Girl,Dresses/Skirts girls,0.909091
58391,719674001,Prairie Conscious Dress,Dress,Blue,Kids Girl,Dresses/Skirts girls,0.909091
80420,801962004,Dahlia,Dress,Blue,Kids Girl,Dresses/Skirts girls,0.909091
44712,681108001,Elva Dress,Dress,Blue,Kids Girl,Dresses/Skirts girls,0.909091

QUERY PRODUCT

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name
46626,686284001,Santa sweater,Sweater,Red,Baby Boy,Knitwear

RECOMMENDATIONS

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name,cosine_similarity
72743,768919003,Turner set,Sweater,Red,Baby Boy,Knitwear,0.909091
34745,643350004,Rudolf sweater,Sweater,Red,Baby Boy,Knitwear,0.909091
65806,745696007,Nils fancy sweater,Sweater,Red,Baby Boy,Knitwear,0.909091
35727,648200002,DELLI sweater,Sweater,Red,Baby Girl,Knitwear,0.818182
47199,688209005,TVP Nils,Sweater,Light Red,Baby Boy,Knitwear,0.818182

QUERY PRODUCT

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name
68433,754256001,GREENVILLE high support bra,Bra,Black,Ladies H&M Sport,Jersey Fancy

RECOMMENDATIONS

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name,cosine_similarity
17183,573150001,KARIN fancy+,Bra,Black,Ladies H&M Sport,Jersey Fancy,1.0
61175,732413001,PANORAMA sports bra,Bra,Black,Ladies H&M Sport,Jersey Fancy,1.0
93493,858407002,Solo Assymetric bra,Bra,Black,Ladies H&M Sport,Jersey Fancy,1.0
32252,634320003,PANORAMA sports bra,Bra,Black,Ladies H&M Sport,Jersey Fancy,1.0
63464,739347001,KARIN MID SUPPORT BRA,Bra,Black,Ladies H&M Sport,Jersey Fancy,1.0

QUERY PRODUCT

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name
68888,755712001,Sune slipover set,Shirt,White,Kids Boy,Shirts

RECOMMENDATIONS

,article_id,prod_name,product_type_name,colour_group_name,section_name,garment_group_name,cosine_similarity
83723,813060015,Princeton ls shirt (TVP),Shirt,White,Kids Boy,Shirts,1.0
83961,814200001,Steve collarless,Shirt,White,Kids Boy,Shirts,1.0
31508,632376003,Kent ss shirt,Shirt,White,Kids Boy,Shirts,1.0
60098,726726001,TP Princeton shirt,Shirt,White,Kids Boy,Shirts,1.0
21079,592039001,Penguin shirt 2SET,Shirt,White,Kids Boy,Shirts,1.0

In [14]:
signature_group_sizes = (
    articles
    .groupby(categorical_cols, observed=True)
    .size()
    .reset_index(name="group_size")
)

signature_group_sizes["group_size"].describe()

count    42882.000000
mean         2.461219
std          5.929257
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max        321.000000
Name: group_size, dtype: float64

In [15]:
{
    "unique_signature_groups": len(signature_group_sizes),
    "products_in_non_unique_groups": signature_group_sizes.loc[
        signature_group_sizes["group_size"] > 1, "group_size"
    ].sum(),
    "max_same_signature_group_size": signature_group_sizes["group_size"].max()
}

{'unique_signature_groups': 42882,
 'products_in_non_unique_groups': np.int64(77870),
 'max_same_signature_group_size': np.int64(321)}

## Initial Findings

The categorical similarity baseline successfully retrieves products from highly relevant product families.  
For example, products with the same product type, colour, section, and garment group are often ranked at the top.

However, the analysis also shows an important limitation:

- 42,882 unique categorical signatures were found among 105,542 articles.
- 77,870 products share their categorical signature with at least one other product.
- The largest identical-signature group contains 321 products.

This indicates that categorical metadata is useful for narrowing down candidate products, but it is often insufficient to rank very similar items within the same category group.

A text-based representation using `prod_name` and `detail_desc` should be explored next to improve fine-grained similarity ranking.